### ISSUE TITLE
function request: AutoZip folders to download

### ISSUE THREAD

**Issue by JeffCorract** [monstaftp/Monsta-FTP#44]
Will it be possible in a further version to download whole folders by zipping them?

**Comment by mjkoch** [comment]
I'd vote for this feature! There's some funkiness with tilde's I think would need to be handled differently before something like this could work. Also, I have on my roadmap for this project to eliminate temp files on the Web server (use the PHP stream IO API wherever possible) and i don't see this being incompatible. Of course, my preference would be for a tarball instead of a zip, but I think I'm in the minority on that.

**Comment by monstaftp** [comment]
Downloading of files and folders has been added in v1.6
